$('#a2').hover(function(){
			$('.a1').css('display','block')
		})
		$('.a1').mouseover(function(){
			$('.a1').css('display','block')
		}).mouseout(function(){
			$('.a1').css('display','none')
		})
		var A4=document.getElementById('a4');
		A4.onfocus=function(){
			A4.placeholder='';
		}
		A4.onblur=function(){
			A4.placeholder='请搜索Opening Cerrmony试试';
		}
		var A5=document.getElementsByClassName('a5')[0].children;
		
		for (a51=0;a51<A5.length;a51++) {
			A5[a51].index=a51;
			A5[a51].onclick=function(){
				for (a52=0;a52<A5.length;a52++) {
					A5[a52].className='';
					A5[a52].style.borderBottom='none';
					A5[a52].style.textDecoration='none';
				}
				this.className='a7';
				this.style.borderBottom='1px yellow solid';
			}
		}
		
		$('.a11').mouseover(function(){
			$('.b1').css('display','block')
		}).mouseout(function(){
			$('.b1').css('display','none')
		})
		$('.b1').mouseover(function(){
			$('.b1').css('display','block')
		}).mouseout(function(){
			$('.b1').css('display','none')
		})
		
		$('.a11:eq(0)').mousemove(function(){
			$('.b2:eq(0)').css('display','block')
		}).mouseout(function(){
			$('.b2:eq(0)').css('display','none')
		})
		$('.a11:eq(1)').mousemove(function(){
			$('.b2:eq(1)').css('display','block')
		}).mouseout(function(){
			$('.b2:eq(1)').css('display','none')
		})
		$('.a11:eq(2)').mousemove(function(){
			$('.b2:eq(2)').css('display','block')
		}).mouseout(function(){
			$('.b2:eq(2)').css('display','none')
		})
		$('.a11:eq(3)').mousemove(function(){
			$('.b2:eq(3)').css('display','block')
		}).mouseout(function(){
			$('.b2:eq(3)').css('display','none')
		})
		$('.a11:eq(4)').mousemove(function(){
			$('.b2:eq(4)').css('display','block')
		}).mouseout(function(){
			$('.b2:eq(4)').css('display','none')
		})
		$('.a11:eq(5)').mousemove(function(){
			$('.b2:eq(5)').css('display','block')
		}).mouseout(function(){
			$('.b2:eq(5)').css('display','none')
		})
		$('.a11:eq(6)').mousemove(function(){
			$('.b2:eq(6)').css('display','block')
		}).mouseout(function(){
			$('.b2:eq(6)').css('display','none')
		})
		$('.a11:eq(7)').mousemove(function(){
			$('.b2:eq(7)').css('display','block')
		}).mouseout(function(){
			$('.b2:eq(7)').css('display','none')
		})
		$('.a11:eq(8)').mousemove(function(){
			$('.b2:eq(8)').css('display','block')
		}).mouseout(function(){
			$('.b2:eq(8)').css('display','none')
		})
		$('.b2:eq(0)').mousemove(function(){
			$('.b2:eq(0)').css('display','block')
		}).mouseout(function(){
			$('.b2:eq(0)').css('display','none')
		})
		$('.b2:eq(1)').mousemove(function(){
			$('.b2:eq(1)').css('display','block')
		}).mouseout(function(){
			$('.b2:eq(1)').css('display','none')
		})
		$('.b2:eq(2)').mousemove(function(){
			$('.b2:eq(2)').css('display','block')
		}).mouseout(function(){
			$('.b2:eq(2)').css('display','none')
		})
		$('.b2:eq(3)').mousemove(function(){
			$('.b2:eq(3)').css('display','block')
		}).mouseout(function(){
			$('.b2:eq(3)').css('display','none')
		})
		$('.b2:eq(4)').mousemove(function(){
			$('.b2:eq(4)').css('display','block')
		}).mouseout(function(){
			$('.b2:eq(4)').css('display','none')
		})
		$('.b2:eq(5)').mousemove(function(){
			$('.b2:eq(5)').css('display','block')
		}).mouseout(function(){
			$('.b2:eq(5)').css('display','none')
		})
		$('.b2:eq(6)').mousemove(function(){
			$('.b2:eq(6)').css('display','block')
		}).mouseout(function(){
			$('.b2:eq(6)').css('display','none')
		})
		$('.b2:eq(7)').mousemove(function(){
			$('.b2:eq(7)').css('display','block')
		}).mouseout(function(){
			$('.b2:eq(7)').css('display','none')
		})
		$('.b2:eq(8)').mousemove(function(){
			$('.b2:eq(8)').css('display','block')
		}).mouseout(function(){
			$('.b2:eq(8)').css('display','none')
		})
		
		$('#c9').mouseover(function(){
			$('#c10').css('display','block')
		}).mouseout(function(){
			$('#c10').css('display','none')
		})